[versions]
kotlin = "1.9.22"
ktor = "2.3.7"
ktoml = "0.5.1"
coroutines = "1.7.3"
ktlint-gradle = "12.0.3"
ktlint = "1.1.0"
clikt = "4.2.1"

[libraries]
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-network = { module = "io.ktor:ktor-network", version.ref = "ktor" }
ktoml-core = { module = "com.akuleshov7:ktoml-core", version.ref = "ktoml" }
ktoml-file = { module = "com.akuleshov7:ktoml-file", version.ref = "ktoml" }
clikt = { module = "com.github.ajalt.clikt:clikt", version.ref = "clikt" }
kotlin-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }

[bundles]
ktor = ["ktor-client-core", "ktor-network"]
ktoml = ["ktoml-core", "ktoml-file"]

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint-gradle" }