name: Build

on:
  push:
    branches: [ "main" ]
    paths:
      - "**.kt"
      - "**.kts"
      - "gradle.properties"
      - ".github/workflows/build.yml"
      - "gradle/**"
  pull_request:
    branches: [ "main" ]
    paths:
      - "**.kt"
      - "**.kts"
      - "gradle.properties"
      - ".github/workflows/build.yml"
      - "gradle/**"

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Check
        run: ./gradlew check

  build:
    name: Build
    needs: check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          dependency-graph: generate-and-submit

      - name: Check
        run: ./gradlew check

      - uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: libc6-dev libx11-dev libxft-dev libxpm-dev libfreetype-dev build-essential
          version: 1.0

      - name: Build
        run: ./gradlew build --scan

      - name: Upload build reports
        uses: actions/upload-artifact@v4
        with:
          name: build-reports
          path: build/reports/