name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      security-events: write

    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libc6-dev libx11-dev libxft-dev libxpm-dev libfreetype-dev build-essential
          version: 1.0

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2 # v2.6.0
        with:
          arguments: build --scan
          dependency-graph: generate-and-submit

      - name: Upload build reports

        uses: actions/upload-artifact@v3

        with:

         name: build-reports

         path: build/reports/


